/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rwu' at '9/30/16 11:49 AM' with Gradle 2.9
 *
 * @author rwu, @date 9/30/16 11:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
